style:
  MaxLineLength:
    maxLineLength: 150

  ReturnCount:
    max: 5

complexity:
  LongParameterList:
    constructorThreshold: 15

  TooManyFunctions:
    thresholdInFiles: 16
    ignorePrivate: true

  ComplexCondition:
    threshold: 10
